# Generated by Django 6.1.1 on 2026-10-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_note_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimator",
            name="assembly_items",
            field=models.PositiveIntegerField(
                default=0, help_text="Furniture to take apart / put together"
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="estimator",
            name="dest_elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimator",
            name="dest_long_carry_ft",
            field=models.PositiveIntegerField(
                default=0, help_text="Walk from door to truck, in feet"
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="dest_parking",
            field=models.CharField(
                choices=[
                    ("dock", "Loading dock"),
                    ("driveway", "Driveway / at the door"),
                    ("street", "Street parking"),
                    ("far", "Far / no parking (shuttle or long walk)"),
                ],
                default="driveway",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="dest_stairs",
            field=models.PositiveIntegerField(default=0, help_text="Flights of stairs"),
        ),
        migrations.AddField(
            model_name="estimator",
            name="drive_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Drive time between locations"
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="move_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimator",
            name="origin_elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="estimator",
            name="origin_long_carry_ft",
            field=models.PositiveIntegerField(
                default=0, help_text="Walk from door to truck, in feet"
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="origin_parking",
            field=models.CharField(
                choices=[
                    ("dock", "Loading dock"),
                    ("driveway", "Driveway / at the door"),
                    ("street", "Street parking"),
                    ("far", "Far / no parking (shuttle or long walk)"),
                ],
                default="driveway",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="origin_stairs",
            field=models.PositiveIntegerField(default=0, help_text="Flights of stairs"),
        ),
        migrations.AddField(
            model_name="estimator",
            name="packing",
            field=models.CharField(
                choices=[
                    ("none", "No packing (customer packs)"),
                    ("partial", "Partial packing (kitchen, fragiles)"),
                    ("full", "Full packing"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="estimator",
            name="special_items",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="estimator",
            name="crew_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estimator",
            name="pound_estimate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estimator",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="estimator",
            name="square_footage",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="CompletedMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_date", models.DateField()),
                ("actual_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("actual_crew_size", models.PositiveIntegerField()),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estimate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="api.estimator",
                    ),
                ),
            ],
        ),
    ]
